// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(CountryContext))]
    partial class CountryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Code");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("backend.Models.InternetStatistic", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasColumnType("text");

                    b.Property<decimal?>("PercentITU")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PercentWB")
                        .HasColumnType("numeric");

                    b.Property<long?>("PopulationCIA")
                        .HasColumnType("bigint");

                    b.Property<int?>("YearCIA")
                        .HasColumnType("integer");

                    b.Property<int?>("YearITU")
                        .HasColumnType("integer");

                    b.Property<int?>("YearWB")
                        .HasColumnType("integer");

                    b.HasKey("CountryCode");

                    b.ToTable("InternetStatistics");
                });

            modelBuilder.Entity("backend.Models.InternetStatistic", b =>
                {
                    b.HasOne("backend.Models.Country", "Country")
                        .WithMany("InternetStatistics")
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("backend.Models.Country", b =>
                {
                    b.Navigation("InternetStatistics");
                });
#pragma warning restore 612, 618
        }
    }
}
